### ISSUE TITLE
How does WebAssembly play a role in this project?

### ISSUE THREAD

**Issue by lilifan** [justjake/quickjs-emscripten#106]
"Javascript/Typescript bindings for QuickJS, a modern Javascript interpreter, compiled to WebAssembly."
As the doc says, QuickJS has been compiled to WebAssembly. But I don't understand how WebAssembly file get executed when I run doc code example in Node.js. Since it don't use the Node.js WASI module. And there is no wasm runtime like wasmtime.
After I learned the source code, I found it works  like:  Node.js  <->  ffi <->  c(quickJs),  so I was wondering where is WebAssembly?
I just learned wasm, and this question maybe silly... Any response will be appreciated!

**Comment by justjake** [comment]
v8 and other JavaScript engines commonly run WebAssembly. WasmTime and WASI are built for running stand alone programs with a `main()` entry point. They aren’t needed here because we’re using the standard WebAssembly support built into the JavaScript engine. There’s an FFI between the JS code running in the JS engine and the WebAssembly code running in the JS engine.

**Comment by lilifan** [comment]
> 

Thank you!
