### ISSUE TITLE
Async property/member help

### ISSUE THREAD

**Issue by damiencourouble** [justjake/quickjs-emscripten#197]
Hello,

Not sure to understand how I can have an async property.

Currently I'm creating an object using
`const obj = context.newObject();`

On this object I can defined a newAsyncifiedFunction without anyProblem
```
 const handle = context.newAsyncifiedFunction(
               "myFunction"
                async (...args) => {
                  // await my stuff
                }
              );
              handle.consume((fn) => {
                context.setProp(obj, "myFunction", fn);
              });
```

And then I create a global object
`
context.setProp(context.global, "MyObject", obj);`

So now  I can evaluate stuff like
`MyObject.myFunction();`

Using 
`await context.evalCodeAsync("MyObject.myFunction();");`

This is great but I can't figure how to do the same with a simple object member/property to be able to evaluate something like
`MyObject.myAsyncProp; `

I'm able to have non async property via though
`   context.setProp(obj, "myNonAsyncProp", context.newString("test"));`

If I use the same approch (newAsyncifiedFunction) attempting to evaluate "MyObject.myAsyncProp" returns 
`function myAsyncProp() { [native code] }`
It obvisously work if I do 

`MyObject.myAsyncProp()`

but I can have that behavior :( 

What I am missing ?
Thanks

**Comment by justjake** [comment]
You can use an asyncified function as a getter via context.defineProp see https://github.com/justjake/quickjs-emscripten/blob/main/doc/quickjs-emscripten-core/classes/QuickJSAsyncContext.md#defineprop

it has the same semantics as Object.defineProperty, in that you can create a property that calls a function when accessed instead of having a static value. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

```typescript
context.defineProp(objHandle, { get: asyncFuncHandle })
```

**Comment by damiencourouble** [comment]
Works like a charm ! thank you :)
