### ISSUE TITLE
QuickJS breaks on OOM in a vm

### ISSUE THREAD

**Issue by vicrazumov** [justjake/quickjs-emscripten#30]
Hi @justjake 

When a vm fails due to the "out of memory" issue, I cannot neither dispose it nor create a new one. It keeps failing with the `RuntimeError: memory access out of bounds`.

**How to reproduce**
1. run `vm.evalScript()` with a code, big enough to violate the memory limit 
2. you will get the `RuntimeError: memory access out of bounds` error
3. try calling `vm.dispose()` or `quickJS.createVm()` - you will be getting the same error

**Comment by justjake** [comment]
Hi @vicrazumov, thanks for reporting this issue. I’m curious about the specifics of your case, some more information or even a failing test would help debug this.

* what runtime environment (Chrome? Node, node version?)
* what memory limit do you set?
* what do you mean by “big enough code”? Do you mean a large script string, or a script that allocates many bytes?

Help reproducing would be appreciated 😄

**Comment by vicrazumov** [comment]
Hi @justjake 

Sorry, should have made it more clear.
1. Chrome
2. I haven't set it explicitly
3. I meant a large script string (my code had a 1+ MB JSON object)

You can try [here](https://vicrazumov.github.io/js-wasm-interpreter/) - replace the `400 + 20` with a big JSON (you can generate one [here](https://www.json-generator.com/#) - use at least 1000 rows)

**Comment by justjake** [comment]
Okay, after some research, I've determined that this issue is because Emscripten's built-in C FFI passes function arguments on the stack, and doesn't resize the stack even when an argument is very large. Details in this 2018 github issue: https://github.com/emscripten-core/emscripten/issues/6860#issuecomment-405818401

The solution is to switch to passing heap-allocated strings to our FFI functions if the strings are large.

**Comment by justjake** [comment]
fix published in https://www.npmjs.com/package/quickjs-emscripten/v/0.11.0
