### ISSUE TITLE
Memory issues on iOS Safari?

### ISSUE THREAD

**Issue by carlosdp** [justjake/quickjs-emscripten#35]
We're having issues with Safari on iOS that seem pretty strange. We're running into a lot of "Out of bounds memory access" errors, which seem like they should have been fixed by moving args onto the heap in 0.11.

More interestingly though, when we switched from manual memory management to using Scopes, we get the `Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1964,JS_FreeRuntime` error on iOS safari, but not on desktop Chrome for the same page.

Any idea why the memory behavior would be different across these two browsers?

**Comment by justjake** [comment]
Hi @carlosdp, thanks for the bug report. I haven't seen these kinds of issues on iOS, but I haven't used Scope there much myself.

My test page here https://jake.tl/projects/quickjs-emscripten seems to work okay on iOS, does using this thingy throw errors for you? On every keystroke, a runtime is created and the script is eval'd. But, there's no exercising of object creation or the Scope APIs.

**Comment by justjake** [comment]
I tried the repro today, but didn't hit any issues. Then, I noticed that your package.json uses a relative path for quickjs-emscripten. I changed to use 0.11.0 from NPM (https://github.com/carlosdp/quickjs-memory-leak/pull/1) and then I encountered a RuntimeError on my iPhone.

Tested on:
* MacBook Pro (15-inch, 2018) / macOS 11.2.3 / Chrome 89.0.4389.128 (Official Build) (x86_64).
  * "undefined" return value.
* MacBook Pro (15-inch, 2018) / macOS 11.2.3 / Safari 14.0.3 (16610.4.3.1.7)
  * "undefined" return value.
* iPhone 12 Pro Max / iOS 14.4.2 
  * `[RuntimeError: abort(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1964,JS_FreeRuntime). Build with -s ASSERTIONS=1 for more info. (evaluating 'new WebAssembly.RuntimeError("abort(" + b + "). Build with -s ASSERTIONS=1 for more info.")')]`

**Comment by carlosdp** [comment]
Yea, sorry about the relative path =P I tried to dig into why this is happening. I suspect potentially it has to do with how the heap is being allocated for the code string? It has to be an external reference, right? And in this example, the only external reference really is the code itself.

**Comment by justjake** [comment]
Ok, there's two issues here:

1. Scope.withScope is obscuring the issue. The block is throwing an error, then the scope tries to dispose the lifetimes it manages, and *that* throws an error that replaces the block error. So, it looks like there's a leak, but the actual buginess is inside the block.
2. Once that is fixed (in https://github.com/justjake/quickjs-emscripten/pull/36) I see the "out of bound" access error.

![image](https://user-images.githubusercontent.com/296279/116824472-4e4eab80-ab3f-11eb-8f9c-0250dd15a288.png)


I googled this one a bit and found some very disturbing issue reports online about iOS WebAssembly problems. I hope we have a programming mistake in the repo, but because things work in other browsers, I'm somewhat inclined to believe this is in part an iOS issue.

- https://github.com/emscripten-core/emscripten/issues/6042
- https://github.com/emscripten-core/emscripten/issues/8121#issuecomment-529021496
- https://bugs.webkit.org/show_bug.cgi?id=181723

**Comment by justjake** [comment]
Interestingly, this issue doesn't occur for me on first load of the page on my iPhone if the tab gets "unloaded" after a couple hours idle. And the frequency of the issue is way down even when hammering the refresh button with newer QuickJS https://github.com/justjake/quickjs-emscripten/pull/37

**Comment by carlosdp** [comment]
Yea, I looked at those Safari issues again, it looks like it has a lot to do with binary size potentially. Tried compiling with `-Oz` to optimize for size, and the error went away.
