### ISSUE TITLE
Apparent memory leak under certain circumstances

### ISSUE THREAD

**Issue by torywheelwright** [justjake/quickjs-emscripten#57]
Hi there, thanks for this really cool project. I've been toying with it, and noticed that the app that I built seems to be leaking a lot of memory. At first I thought I was just doing something wrong, so I tried to scope it down to the simplest example that leaked, and ended up with [this](https://github.com/torywheelwright/quickjs-emscripten-memory-leak-repro). It looks like `vm.dump` is the problem; if I comment that line out, I don't see memory growth. It's still possible I'm doing something wrong, but I think this is real?

You can run the test by running `yarn && yarn build && yarn start`, and it will periodically print the "external" memory usage, as per process.memoryUsage. It only takes a few moments to notice the trend, and if you let it run overnight, it will eventually crash.

**Comment by justjake** [comment]
Thank you for the detailed bug report. I suspect the issue is that we don’t JS_FreeCString here: https://github.com/justjake/quickjs-emscripten/blob/8b177552efcd24394a2f31655e3101f47d26a37f/c/interface.c#L429

I think this is a simple issue to fix, we need to strdup the result and the free it, then we can return the strdup string instead. QTS_GetString already does the right thing I think: https://github.com/justjake/quickjs-emscripten/blob/8b177552efcd24394a2f31655e3101f47d26a37f/c/interface.c#L307

- can you try running your test generating and dumping big *string* values? That would validate the string copy logic is correct
- Or, take a shot at making the change suggested above?

**Comment by justjake** [comment]
Hm my theory about strdup is wrong since this function is calling down to QTS_GetString already.

**Comment by torywheelwright** [comment]
Wow, thanks for fixing this so fast. So far so good!
