### ISSUE TITLE
Is it possible to limit CPUtime?

### ISSUE THREAD

**Issue by BartTactick** [justjake/quickjs-emscripten#69]
Hi there,

This project looks promising to me!
But im wondering if its possible to limit the CPU time.
Like:
runtime.setCPUTimeLimit(miliseconds here)

**Comment by justjake** [comment]
Hey @BartTactick,

how do you expect this to work? There’s an option to run a function periodically that can interrupt execution. You can probably use that to implement the time-based semantics you need. There’s an example of a deadline based interrupt in the README, see `shouldInterrupt: …` here: https://github.com/justjake/quickjs-emscripten#safely-evaluate-javascript-code

You can add this to a Runtime using `setInterruptHandler`: https://github.com/justjake/quickjs-emscripten/blob/main/doc/classes/QuickJSRuntime.md#setinterrupthandler

**Comment by BartTactick** [comment]
Hey @justjake ,

Basicly the way Cloudflare workers work: https://developers.cloudflare.com/workers/platform/pricing/
So lets say your doing a heavy loop it will count how long you have used the CPU.
But when the CPU is idle (for example waiting for a network response or something) it wont count anything.
In the end you would have a the MS that the script has ran.
And based on that you could stop the execution from happening i guess.

**Comment by justjake** [comment]
To clarify, you want to count the wall-clock time taken by every call to a VM function that executes code in the VM, and possibly interrupt execution once a certain limit is reached, but when the VM exits because it’s awaiting a host Promise (ie, IO inside an async loop running in the VM) you don’t want to count that time?

I think this is very doable without changes to the library today. The VM does not block the host thread while it is awaiting. And, you always control when the VM resumes execution after a host promise resolves a VM promise. So you can save a time stamp before every call into the VM and after every call into the VM exits, and use those to account for the CPU time spent. Additionally, you could use the interrupt handler to interrupt if `(timeSoFar + (Date.now() - startTimeOfThisCall) > MAX_TIME)`.

**Comment by BartTactick** [comment]
Im pointing towards CPU time or user-cpu time if your looking at this stackoverflow post:
"The user-cpu time and system-cpu time are pretty much as you said - the amount of time spent in user code and the amount of time spent in kernel code."
 > https://stackoverflow.com/a/7335965

**Comment by justjake** [comment]
I think my previous post describes a way to capture user-cpu time if you define user-cpu time as “evaluating code in the vm”, which I think seems reasonable.

**Comment by BartTactick** [comment]
> I think my previous post describes a way to capture user-cpu time if you define user-cpu time as “evaluating code in the vm”, which I think seems reasonable.

I will look into it. Thank you so far!
