### ISSUE TITLE
Question: how to inject setInterval?

### ISSUE THREAD

**Issue by psawaya** [justjake/quickjs-emscripten#93]
First off -- this library is amazing. My hats off to @justjake and all other contributors for doing this. :)

I'd like to inject a simple `setInterval` function into my VM, and I'm curious as to how to do that.

I tried the below:
```ts
  private injectSetInterval() {
    const setIntervalHandler = this.vm.newFunction('setInterval', (funcHandle, timeoutHandle) => {
      const timeout = this.vm.getNumber(timeoutHandle);
      setInterval(() => {
        this.vm.callFunction(funcHandle, {});
      }, timeout);
    });
    this.vm.setProp(this.vm.global, 'setInterval', setIntervalHandler);
    setIntervalHandler.dispose();
  }
```

And I'm getting a `QuickJSUseAfterFree: Lifetime not alive` error.

I'm guessing the tricky thing I'm trying to figure out here is how to store a handle to a function value internal to the VM and call it later in my node-native `setInterval`. Would appreciate any help! Thanks :)

**Comment by justjake** [comment]
you can add `const longLivedFunctionHandle = funcHandle.dup()` before the function implementation returns. You can then stash the longLivedFunctionhandle in a `Map` somewhere, keyed by the interval ID, and then dispose of the `longLivedFunctionhandle` whenever you clear the interval.

For security sake, make sure you have some control over how many intervals the guest can schedule! Scheduling too many intervals could use all your CPU, without any way for your host to avoid exhaustion. I also recommend putting a maximum duration on the interval, so that it's unscheduled after some time limit on the host. Finally, be sure to return the result handle ID to your guest, in case the guest wants to clearInterval on its own.

**Comment by justjake** [comment]
We should update the doc comment for `newFunction` to include those instructions.

**Comment by psawaya** [comment]
Amazing! Appreciate the quick response and the help. Advice is smart, too. :)

Quick double-check: after we're done with the callback (eg, clearInterval is called), we want to call `longLivedFunctionHandle.dispose`, right?

**Comment by justjake** [comment]
> Amazing! Appreciate the quick response and the help. Advice is smart, too. :)
> 
> Quick double-check: after we're done with the callback (eg, clearInterval is called), we want to call `longLivedFunctionHandle.dispose`, right?

Yes, you'd want to dispose the function once it's cleared, and remove it from the map (or wherever you store it)
